version: "3"
services:
  client:
    build: frontend.v2/
    ports:
      - "40080:80"

  server:
    build: backend/
    ports:
      - "45080:80"
      - "45081:81"
    depends_on: 
      - db

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: masterkey
    ports:
      - "45432:5432"
    volumes: 
      - "./database/init-db/:/docker-entrypoint-initdb.d/"