version: "3"
services:
  client:
    build: frontend.v2/
    ports:
      - "40080:80"    
    depends_on: 
      - server
  

  server:
    build: backend.v2/backend.v2
    ports:
      - "45080:80"
      - "45081:81"
    depends_on: 
      - postgre
      - mail-server

  mail-server:
    image: juanluisbaptiste/postfix:latest
    environment: 
      SMTP_SERVER: "localhost"
      SMTP_USERNAME: "smtp"
      SMTP_PASSWORD: "masterkey"
      SERVER_HOSTNAME: "bookolog.ru"
      SMTP_PORT: 587

  postgre:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: masterkey
    ports:
      - "45432:5432"
    volumes: 
      - "./database/init-db/:/docker-entrypoint-initdb.d/"


# firewall-cmd --zone=public --add-masquerade --permanent
# firewall-cmd --permanent --zone=public --add-rich-rule='rule family=ipv4 source address=172.18.0.0/16 accept'
# firewall-cmd --reload