version: "3"
services:
  client:
    image: docker.pkg.github.com/afferenslucem/bookolog/client:latest
    ports:
      - "127.0.0.1:40080:80"
    depends_on:
      - server

  server:
    image: docker.pkg.github.com/afferenslucem/bookolog/server:latest
    ports:
      - "127.0.0.1:45080:80"
      - "127.0.0.1:45081:81"
    depends_on:
      - postgre
      - postfix
    volumes:
      - "./backend.v2/backend.v2/appsettings.json:/app/appsettings.json"
      - "/imageStorage:/imageStorage"

  postfix:
    image: boky/postfix
    environment:
      POSTFIX_myhostname: hrodvitnir.pw
      POSTFIX_myorigin: hrodvitnir.pw
      ALLOWED_SENDER_DOMAINS: hrodvitnir.pw
    ports:
      - "45587:587"

  postgre:
    image: postgres:14-bullseye
    environment:
      POSTGRES_PASSWORD: masterkey
    ports:
      - "127.0.0.1:45432:5432"
    volumes:
      - "./database/init-db/:/docker-entrypoint-initdb.d/"
