version: "3"
services:
  client:
    build: frontend.v2/
    ports:
      - "40080:80"    
    depends_on: 
      - server
    network_mode: host
  

  server:
    build: backend.v2/backend.v2
    ports:
      - "45080:80"
      - "45081:81"
    depends_on: 
      - db
    network_mode: host

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: masterkey
    ports:
      - "45432:5432"
    volumes: 
      - "./database/init-db/:/docker-entrypoint-initdb.d/"