version: "3"
services:
  client:
    build:
      context: frontend.v3/
      dockerfile: DockerfileTest
    volumes: 
      - "./frontend.v3:/app"
    command: sh -c "npm ci && npm test"    
    working_dir: /app
    environment: 
      NG_CLI_ANALYTICS: 'off'