version: "3"
services:
  client:
    build: 
      dockerfile: DockerfileProd
      context: frontend.v2/
    ports:
      - "40080:80"    
    depends_on: 
      - server
  

  server:
    build: 
      dockerfile: DockerfileProd
      context: backend.v2/backend.v2/
    ports:
      - "45080:80"
      - "45081:81"
    depends_on: 
      - postgre
      - postfix
    volumes: 
      - "C:\\Users\\a.shakirov\\Pictures\\Images:/imageStorage"

  postfix:
    image: boky/postfix
    environment:
      POSTFIX_myhostname: hrodvitnir.pw
      POSTFIX_myorigin: hrodvitnir.pw
      ALLOWED_SENDER_DOMAINS: hrodvitnir.pw
    ports:
      - "45587:587"

  postgre:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: masterkey
    ports:
      - "45432:5432"
    volumes: 
      - "./database/init-db/:/docker-entrypoint-initdb.d/"

