export const books = [{
    authors: ["Андрей Круз", "Андрей Царев"],
    genre: "Фантастика",
    name: "Земля лишних. Последний борт на Одессу",
    status: 0,
    tags: ["Другие миры", "попаданцы", "боевая фантастика"],
    type: 2,
    note: 'Книга про добрых авантюристов.',
},{
    authors: ["Андрей Круз", "Андрей Царев"],
    totalUnits: 100,
    doneUnits: 20,
    endDate: "2020-08-31",
    endDateYear: "2020",
    endDateMonth: "8",
    endDateDay: "31",
    genre: "Фантастика",
    name: "Земля лишних. Два билета туда",
    startDate: "2020-08-27",
    startDateYear: "2020",
    startDateMonth: "8",
    startDateDay: "27",
    status: 2,
    tags: ["Другие миры", "попаданцы", "боевая фантастика"],
    type: 2,
    note: 'Главные персонажи очень душевные'
},{
    authors: ["Андрей Круз"],
    doneUnits: 332,
    genre: "Фантастика",
    name: "Ар Деко",
    note: "Про мафию",
    startDate: "2020-09-16",
    startDateYear: "2020",
    startDateMonth: "9",
    startDateDay: "16",
    status: 1,
    tags: ["Мафия", "боевая фантастика"],
    totalUnits: 710,
    type: 2,
}];