version: "3"
services:
  client:
    build: ../frontend.v2/
    ports:
      - "30080:80"    
    depends_on: 
      - server
  

  server:
    build: ../backend.v2/backend.v2
    ports:
      - "35080:80"
      - "35081:81"
    depends_on: 
      - postgre

  postgre:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: masterkey
    ports:
      - "35432:5432"
    volumes: 
      - "./bookolog_test.sql:/docker-entrypoint-initdb.d/bookolog_test.sql.back"
      - "./create-db.sh:/docker-entrypoint-initdb.d/create-db.sh"

