export const USER_LOGIN_ACTION = 'USER_LOGIN_ACTION';
export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION';
export const USER_RECOVER_ACTION = 'USER_RECOVER_ACTION';

export const USER_LOGIN_MUTATION = 'USER_LOGIN_MUTATION';
export const USER_LOGOUT_MUTATION = 'USER_LOGOUT_MUTATION';

export const USER_LOGGED_IN_GETTER = 'USER_LOGGED_IN_GETTER';

// Books

export const BOOKS_SYNC_ACTION = 'BOOKS_SYNC_ACTION';
export const BOOKS_CLEAR_ACTION = 'BOOKS_CLEAR_ACTION';
export const BOOK_ADD_ACTION = 'BOOK_ADD_ACTION';
export const BOOK_UPDATE_ACTION = 'BOOK_UPDATE_ACTION';
export const BOOK_DELETE_ACTION = 'BOOK_DELETE_ACTION';
export const BOOK_GET_BY_GUID_ACTION = 'BOOK_GET_BY_GUID_ACTION';

export const BOOKS_SAVE_MUTATION = 'BOOKS_SAVE_MUTATION';
export const BOOKS_CLEAR_MUTATION = 'BOOKS_CLEAR_MUTATION';
export const BOOK_UPDATE_MUTATION = 'BOOK_UPDATE_MUTATION';
export const BOOK_ADD_MUTATION = 'BOOK_ADD_MUTATION';
export const BOOK_DELETE_MUTATION = 'BOOK_DELETE_MUTATION';

export const BOOKS_IN_PROGRESS_GETTER = 'BOOKS_IN_PROGRESS_GETTER';
export const BOOKS_DONE_GETTER = 'BOOKS_DONE_GETTER';
export const BOOKS_TO_READ_GETTER = 'BOOKS_TO_READ_GETTER';

export const BOOKS_GENRES_COUNT_GETTER = 'BOOKS_GENRES_COUNT_GETTER';
export const BOOKS_TAGS_COUNT_GETTER = 'BOOKS_TAGS_COUNT_GETTER';
export const BOOKS_AUTHORS_COUNT_GETTER = 'BOOKS_AUTHORS_COUNT_GETTER';

export const NETWORK_ERROR = 'Error: Network Error';