export const USER_LOGIN_ACTION = 'USER_LOGIN_ACTION';
export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION';
export const USER_RECOVER_ACTION = 'USER_RECOVER_ACTION';
export const USER_SAVE_ACTION = 'USER_SAVE_ACTION';
export const USER_SYNC_BOOKS_ACTION = 'USER_SYNC_BOOKS_ACTION';
export const USER_SYNC_DATA_ACTION = 'USER_SYNC_DATA_ACTION';

export const USER_LOGIN_MUTATION = 'USER_LOGIN_MUTATION';
export const USER_LOGOUT_MUTATION = 'USER_LOGOUT_MUTATION';
export const USER_SET_EMAIL_MUTATION = 'USER_SET_EMAIL_MUTATION';

export const USER_LOGGED_IN_GETTER = 'USER_LOGGED_IN_GETTER';

// Books

export const BOOKS_SYNC_ACTION = 'BOOKS_SYNC_ACTION';
export const BOOKS_LOAD_ACTION = 'BOOKS_LOAD_ACTION';
export const BOOKS_LOAD_LOCAL_ACTION = 'BOOKS_LOAD_LOCAL_ACTION';
export const BOOKS_CLEAR_ACTION = 'BOOKS_CLEAR_ACTION';
export const BOOK_ADD_ACTION = 'BOOK_ADD_ACTION';
export const BOOK_UPDATE_ACTION = 'BOOK_UPDATE_ACTION';
export const BOOK_DELETE_ACTION = 'BOOK_DELETE_ACTION';
export const BOOK_GET_FRESHEST_BOOK_BY_GUID_ACTION = 'BOOK_GET_FRESHEST_BOOK_BY_GUID_ACTION';
export const BOOK_GET_AND_REFRESH_BY_GUID_ACTION = 'BOOK_GET_AND_REFRESH_BY_GUID_ACTION';

export const BOOKS_SAVE_MUTATION = 'BOOKS_SAVE_MUTATION';
export const BOOKS_CLEAR_MUTATION = 'BOOKS_CLEAR_MUTATION';
export const BOOK_UPDATE_MUTATION = 'BOOK_UPDATE_MUTATION';
export const BOOK_ADD_MUTATION = 'BOOK_ADD_MUTATION';
export const BOOK_DELETE_MUTATION = 'BOOK_DELETE_MUTATION';

export const BOOKS_IN_PROGRESS_GETTER = 'BOOKS_IN_PROGRESS_GETTER';
export const BOOKS_DONE_GETTER = 'BOOKS_DONE_GETTER';
export const BOOKS_TO_READ_GETTER = 'BOOKS_TO_READ_GETTER';

export const BOOKS_GENRES_COUNT_GETTER = 'BOOKS_GENRES_COUNT_GETTER';
export const BOOKS_TAGS_COUNT_GETTER = 'BOOKS_TAGS_COUNT_GETTER';
export const BOOKS_AUTHORS_COUNT_GETTER = 'BOOKS_AUTHORS_COUNT_GETTER';

// Connection

export const CONNECTION_ONLINE_MUTATION = 'CONNECTION_ONLINE_MUTATION';
export const CONNECTION_OFFLINE_MUTATION = 'CONNECTION_OFFLINE_MUTATION';
export const CONNECTION_LOAD_START_MUTATION = 'CONNECTION_LOAD_START_MUTATION';
export const CONNECTION_LOAD_FINISH_MUTATION = 'CONNECTION_LOAD_FINISH_MUTATION';
export const CONNECTION_LOAD_START_ACTION = 'CONNECTION_LOAD_START_ACTION';
export const CONNECTION_LOAD_FINISH_ACTION = 'CONNECTION_LOAD_FINISH_ACTION';
export const CONNECTION_SAVE_LOAD_TIMER_MUTATION = 'CONNECTION_SAVE_LOAD_TIMER_MUTATION';
export const CONNECTION_REMOVE_LOAD_TIMER_NUTATION = 'CONNECTION_REMOVE_LOAD_TIMER_NUTATION';

export const CONNECTION_ONLINE_ACTION = 'CONNECTION_ONLINE_ACTION';
export const CONNECTION_OFFLINE_ACTION = 'CONNECTION_OFFLINE_ACTION';

// Notification

export const NOTIFICATION_SHOW_MUTATION = 'NOTIFICATION_SHOW_MUTATION';
export const NOTIFICATION_HIDE_MUTATION = 'NOTIFICATION_HIDE_MUTATION';

export const NOTIFICATION_SHOW_ACTION = 'NOTIFICATION_SHOW_MUTATION';
export const NOTIFICATION_WARNING_ACTION = 'NOTIFICATION_WARNING_ACTION';
export const NOTIFICATION_SUCCESS_ACTION = 'NOTIFICATION_SUCCESS_ACTION';
export const NOTIFICATION_DANGER_ACTION = 'NOTIFICATION_DANGER_ACTION';
export const NOTIFICATION_INFO_ACTION = 'NOTIFICATION_INFO_ACTION';


export const NETWORK_ERROR = 'Error: Network Error';
export const BAD_REQUEST_ERROR = 'Error: Request failed with status code 404';