POST https://localhost:45081/auth/login
Content-Type: application/json

{
    "login": "admin",
    "password": "masterkey"
}

###############################################

POST http://localhost:45080/auth/register
Content-Type: application/json

{
  "login": "kruz2",
  "email": "kruz2@gmail.com",
  "password": "nullnullnull"
}

