POST http://localhost:35080/auth/login
Content-Type: application/json

{
    "login": "fullUser",
    "password": "masterkey"
}

###############################################

POST http://localhost:45080/auth/register
Content-Type: application/json

{
  "login": "kruz2",
  "email": "kruz2@gmail.com",
  "password": "nullnullnull"
}

###############################################

GET http://localhost:5000/user/2
