POST http://localhost:5000/authenticate/login
Content-Type: application/json

{
    "login": "admin",
    "password": "masterkey"
}

###############################################

GET http://localhost:5000/book/all

###############################################

GET http://localhost:5000/book/2656eb9e-4ffe-4a52-a471-70b193090ed2

###############################################

POST http://localhost:5000/book
Content-Type: application/json

{
"guid": "c6c0f032-e619-4974-ad1b-8eda02444d3f",
"name": "Test",
"authors": [
    "Кайл Иторр",
    "Test"
],
"year": 2020,
"status": 0,
"tags": [
    "боевик",
    "другие миры",
    "авантюра"
],
"doneUnits": 456,
"totalUnits": 100,
"genge": "фантастика",
"startDate": "2020-08-11T00:00:00",
"modifyDate": null,
"endDate": null,
"type": 0,
"note": null,
"userId": 1
}