name: Client tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Client tests
      run: cd frontend.v3 && docker-compose build client-test && docker-compose up client-test
