name: Client tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Client tests
      run: docker build . --file ./frontend.v3/Dockerfile --tag client-tests:$(date +%s)
