name: Bookolog Unit Tests

on:
  push:
    branches: [ master, develop, release/* ]


jobs:
  client-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend.v3

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Tests client use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build ui-kit
      - run: npm pack ./dist/ui-kit
      - run: npm install ui-kit-0.0.1.tgz
      - run: npm run build
      - run: npm run test:prod

  ui-kit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend.v3

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Tests client use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present -- --prod ui-kit
      - run: npm run test:prod -- ui-kit

  client-linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend.v3

    steps:
      - uses: actions/checkout@v2
      - name: Lint client
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run lint

  server-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build server tests Docker image
        run: docker build -t bookolog/tests backend.v2 --file backend.v2/DockerfileTests
        
      - name: Run server tests
        run: docker run bookolog/tests






