name: Bookolog E2E Tests

on:
  push:
    branches: [ master, develop, release/* ]


jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2
      - name: Build testing images
        run: docker-compose -f docker-compose.e2e.yml build
        
      - name: Run e2e tests
        run: docker-compose -f docker-compose.e2e.yml up e2e






