name: Bookolog Tests

on:
  push:
    branches: [ master, develop ]


jobs:
  client-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend.v3

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Tests client use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:prod

  server-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build server tests Docker image
        run: docker build -t bookolog/tests backend.v2 --file backend.v2/DockerfileTests
        
      - name: Run server tests
        run: docker run bookolog/tests






