name: Server Tests

on:
  push:
    branches: [ develop, master, tests ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t bookolog/tests backend.v2 --file DockerfileTests 
        docker run bookolog/tests
